name: Check pull request
on:
  workflow_call:
    inputs:
      summary:
        description: 'The summary of the pull request'
        required: true
        type: string
    outputs:
      version-bump:
        description: 'The version bump'
        value: ${{ jobs.check-pull-request.outputs.version-bump }}
jobs:
  check-pull-request:
    name: Check pull request
    runs-on: ubuntu-latest
    outputs:
      version-bump: ${{ steps.check-pull-request.outputs.version-bump }}
    steps:
      - name: Check pull request
        id: check-pull-request
        # env:
        #   summary: ${{ inputs.summary }}
        run: |
          summary="fix: asdsfdafdsa"
          if [[ "$summary" =~ ^.*# (BREAKING[ -]CHANGES).* ]]; then
            version-bump="major"
          elif [[ "$summary" =~ ^.*# (Feature).* ]]; then
            version-bump="minor"
          elif [[ "$summary" =~ ^.*# (Build|Bug Fix|Performance|Refactor).* ]]; then
            version-bump="patch"
          else
            version-bump="none"
          fi
          echo "version-bump: $version-bump"
          echo "version-bump=$version-bump" >> $GITHUB_ENV