name: Release

on:
  workflow_call:
    inputs:
      version:
        description: 'Version to release'
        required: true
        type: string
      pr_body:
        description: 'Pull request body'
        required: true
        type: string
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download windows build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-windows
          path: build-windows
      
      - name: Download android build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-android
          path: build-android

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          name: v${{ github.event.inputs.version }}
          tag: v${{ github.event.inputs.version }}
          commit: ${{ github.sha }}
          makeLatest: true
          draft: false
          prerelease: false
          body: |
            Release ${{ github.event.inputs.version }}
            ${{ github.event.inputs.pr_body }}
          artifacts: |
            build-windows/*
            build-android/*
